- name: Copy patch scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - { src: 'setup.sh', dest: '/tmp/setup.sh' }
